Fixed discriminator display bug
peterhanania/Discord-Package pull request #22
Opened 2022-10-24 15:45 UTC by farkon00

Fixed bug with discriminator displaying without zeros. Eg my discriminator is #0500, but discord-package was displaying it as #500.

2022-10-24 15:57 UTC, farkon00 commented
Diff
![image](https://user-images.githubusercontent.com/59134591/197571221-3cd9426d-d1e2-4de7-9de8-0e5bf2baf9ce.png)

2022-10-24 21:38 UTC, 3kh0 approved these changes
On the preview it works!

2022-10-24 22:03 UTC, peterhanania requested changes
Thank you for your PR.

before updating can you make sure all discriminators work? If you could try editing your disc several times and make sure it works and let me know if you find another bug, if not reply to this and I will approve.

2022-10-25 07:29 UTC, farkon00 commented
@peterhanania Yes i checked, but without the app. Just pasted discriminator code into regular ts script and replaced getting discriminator from data object with a varaible. It worked.

2022-10-28 21:44 UTC, peterhanania approved these changes

2022-10-28 21:45 UTC, peterhanania commented
DM me for your role :)

2022-10-28 21:45 UTC, merged